spring:
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: development
    include: collections
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://110.31.10.175:5432/manifoldcf"
    username: manifoldcf
    password: manifoldcf
    tomcat:
      maxActive: 15
      maxIdle: 10
      minIdle: 5
      initialSize: 2
  data.solr.zk-host: 110.31.10.175:12181,110.31.10.175:22181,110.31.10.175:32181
  session.store-type: NONE
  thymeleaf:
    mode: LEGACYHTML5
  main:
    allow-bean-definition-overriding: true

security:
  basic:
    enabled: false

app:
  account:
    password.minLength: 6

